[GLOBAL]
pants_version = "2.12.0"
backend_packages = [
  "pants.backend.experimental.python",
  "pants.backend.experimental.python.lint.autoflake",
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
]

[anonymous-telemetry]
enabled = true
repo_id = "EFE51B67-B2F3-4FCF-A44A-10CAE24B63B7"

[python]
interpreter_constraints = [">=3.8, <3.10"]
enable_resolves = true

[python.resolves]
python-default = "3rdparty/requirements.lock"
